### ISSUE TITLE
Error when giving items to new 5.4.0 Party Sheet but item transfer works properly

### ISSUE THREAD

**Issue by apoapostolov** [reonZ/pf2e-giveth#11] opened 2023-08-29 17:42 UTC
Error message appears but the item transfer works properly both ways. 

![image](https://github.com/reonZ/pf2e-giveth/assets/4083812/82427da1-0343-45d9-a66e-5cd85531ec88)

**Comment by reonZ** [comment] 2023-08-30 13:04
I need more details on the error, because the module shouldn't do anything when interacting with the party actor, be it giving an item to or taking an item from it.

It only works with player-owned linked `Character`, `NPC` and `Vehicle` actors.

**Comment by git-kor-av** [comment] 2023-08-30 19:16
I don't think this is a Giveth problem.  I still need to test with no modules enabled, but I'm 99% certain this problem has nothing to do with Giveth.

The error is reproducible without Giveth enabled:
- Create 3 actors
- Place all 3 tokens on the active scene
- Open all 3 actors and display their inventor
- Put an item, say a dagger or mace on one actor
- Drag the item from one actor, to the next, and continue to repeat that until the error occurs

This is the error message that will appear:
![image](https://github.com/reonZ/pf2e-giveth/assets/32276185/112c63c4-e652-46e7-8347-d60cc4e8f558)

**Comment by git-kor-av** [comment] 2023-08-30 21:44
Definitely not a Giveth bug, I was able to reproduce it consistently and the problem is actually with Dice Tray of all things.  Details here if you're interested:  https://discord.com/channels/880968862240239708/880969241552113695/1146534391145828373

**Comment by reonZ** [comment] 2023-08-30 22:52
alright, i am closing this issue then, thanks for the help.

**Closed as completed by reonZ** 2023-08-30 22:52 UTC
